### PR TITLE
Personal Item: Duna, Burg, Hisses and Material's Plushies. The True Mass of Plushies Emerges.

### PR DESCRIPTION
**Pull request by Coolsurf6**
## About the PR
Added a personal item for 'Anxeeth-Duna' for Ariphylor.
Added a personal item for 'Only-Sees-Burgundy' for SpliTistic.
Added a personal item for 'Hisses-At-Inconvenience' for Slugcta.
Added a personal item for 'Steals-The-Materials' for Jacketed.

## Why / Balance
Personal Items, FOR ALL. I CAN'T BE STOPPED AND WILL NOT BE STOPPED.

## Technical details
Added new YML code using the base lizard plushie item (and a snake plushie item for Burgandy). Edited images of the weh plushie including the headsprite done by Slugcta and Jacketed!

Added all these plushies in the same PR so that there are less conflicts as all of these wanted to be added at the same time.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Anxeeth-Duna's plushie. 
- add: Added Only-Sees-Burgundy's plushie. Rum (unfortunately) not included.
- add: Added Hisses-At-Inconvenience's plushie. Hiss not included. 
- add: Added Steals-The-Materials's plushie.

### CODE REVIEW

**Comment by Coolsurf6** [comment]
Todo:

- [ ] Get the sprites for the Steals-The-Materials Plushies.
- [ ] Get some quips if wanted for the changelog
- [ ] Get images with plushies (while they are extreamly well armed)
- [X] *hisses!

**Comment by Coolsurf6** [comment]
> 1. This should probably be atomised(makes it easier to review(I think?)
> 
>     2. Umbra doesn’t have changelogs
> 
>     3. You seem to have some weird whitespace changes

I am not sure what you mean by atomised. Having each plushie done one at a time causes conflicts and I thought since I had two people ask for plushies literally at the same time, it was easier to get all of these checked at once. 

Also Umbra doesn't have changelogs? Damn...

Also those whitespace changes KEEP happening. I keep trying to block the changes but it seems some have gone though. I am unsure why my KDE is causing this...

**Comment by Boaz1111** [comment]
Atomising is splitting things up into separate pr’s

**Comment by Coolsurf6** [comment]
> Atomising is splitting things up into separate pr’s

I'll ask Alex as it would mean a whole bunch of conflict fixing since all these are adding are separate plushie sprites and not a bunch of separable game mechanics.

**Comment by Boaz1111** [comment]
might also want to ask a GM. Personal Items need GM approval as well, after all

**Comment by Boaz1111** [comment]
> > I am not sure what you mean by atomised. Having each plushie done one at a time causes conflicts and I thought since I had two people ask for plushies literally at the same time, it was easier to get all of these checked at once.
> > I'll ask Alex as it would mean a whole bunch of conflict fixing since all these are adding are separate plushie sprites and not a bunch of separable game mechanics.
> 
> Please just atomize it and the maintainer looking at the PR will handle the merge conflicts themselves about 90% of the time, or help you resolve them. For this PR, I will permit it not being atomized, but in the future please atomize it. It makes reviewing easier and makes others working on similar files have an easier time. In this case its not a huge deal either way.
> 
> > Also Umbra doesn't have changelogs? Damn...
> 
> For most things, no. We treat the github chat as our changelog, for major things however there can still be change logs. Just label it if you think its a major enough change and we'll decide if its worth bringing up.
> 
> > Also those whitespace changes KEEP happening. I keep trying to block the changes but it seems some have gone though. I am unsure why my KDE is causing this...
> 
> Your IDE might have a setting to disable whitespace changes like this. These changes are permissible, but still look into disabling it if possible, just so you know where.
> 
> > might also want to ask a GM. Personal Items need GM approval as well, after all
> 
> Any personal item PRs are already labeled internally for GMs to look at them. The only time(s) you need to really ask in advance is if you want to avoid possibly getting denied at the PR stage.
 I was more so saying to also ask a GM if it needed to be atomised

**Comment by Coolsurf6** [comment]
The massive nuke of plushies will be put down this day. May they be valiantly remembered for their sacrifices.

**Pull request closed without merging**
