### PR TITLE
Fix that one comment I missed on PR #229

### PR DESCRIPTION
**Pull request by ArtisticRoomba**
## About the PR
Comments some umbra changes that I missed in PR #229 
## Why / Balance

I forgor to leave comments for umbra changes.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
Non player facing, no CL no fun

### CODE REVIEW

**Comment by ArtisticRoomba** [comment]
aright goober you can do it merge this one PR, I believe in you :)

**Comment by Coolsurf6** [comment]
> aright goober you can do it merge this one PR, I believe in you :)

:trollface:

**Comment by Coolsurf6** [comment]
You may need to look at fixing the merge conflicts first.

**Comment by ArtisticRoomba** [comment]
its as simple as that

**Review by Coolsurf6 — APPROVED** [review]
Checked other sections for Umbra Comments, all seem to be okay now.

Works in game, definitely didn't explode many death- internal affair agents to check all their equipment.

**Pull request merged**
