### PR TITLE
Paper signatures

### PR DESCRIPTION
**Pull request by TsjipTsjip**
Merges pen signing from https://github.com/DeltaV-Station/Delta-v/pull/1172 .

### CODE REVIEW

**Review by Simyon264 — CHANGES_REQUESTED** [review]
Signing results in a bad popup and the following error(s):
```
[ERRO] loc: "en-US"/"zzzz-the": "System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Robust.Shared.GameObjects.EntityUid'.
   at Robust.Shared.Localization.LocalizationManager.FuncProper(LocArgs args) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.Functions.cs:line 310
   at Robust.Shared.Localization.LocalizationManager.CallFunction(LocFunction function, FluentBundle bundle, IList`1 positionalArgs, IDictionary`2 namedArgs) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.Functions.cs:line 352
   at Robust.Shared.Localization.LocalizationManager.<>c__DisplayClass62_0.<AddCtxFunction>b__0(IList`1 args, IDictionary`2 options) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.Functions.cs:line 330
   at Linguini.Bundle.Resolver.WriterHelpers.Write(IInlineExpression self, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 166
   at Linguini.Bundle.Resolver.WriterHelpers.TryWrite(IExpression expression, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 73
   at Linguini.Bundle.Resolver.ResolverHelpers.Resolve(IInlineExpression self, Scope scope) in /_/Linguini.Bundle/Resolver/ResolverHelpers.cs:line 65
   at Linguini.Bundle.Resolver.WriterHelpers.TryWrite(IExpression expression, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 77
   at Linguini.Bundle.Resolver.Scope.MaybeTrack(TextWriter writer, Pattern pattern, IExpression expr) in /_/Linguini.Bundle/Resolver/Scope.cs:line 62
   at Linguini.Bundle.Resolver.WriterHelpers.Write(Pattern pattern, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 50
   at Linguini.Bundle.FluentBundle.TryGetMsg(String id, String attribute, IDictionary`2 args, IList`1& errors, String& message) in /_/Linguini.Bundle/FluentBundle.cs:line 241
   at Linguini.Bundle.FluentBundle.TryGetAttrMsg(String msgWithAttr, IDictionary`2 args, IList`1& errors, String& message) in /_/Linguini.Bundle/FluentBundle.cs:line 210
   at Robust.Shared.Localization.LocalizationManager.TryGetString(String messageId, String& value, Dictionary`2 args, FluentBundle bundle, CultureInfo culture) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.cs:line 219"
[ERRO] loc: "en-US"/"zzzz-the": "System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Robust.Shared.GameObjects.EntityUid'.
   at Robust.Shared.Localization.LocalizationManager.FuncProper(LocArgs args) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.Functions.cs:line 310
   at Robust.Shared.Localization.LocalizationManager.CallFunction(LocFunction function, FluentBundle bundle, IList`1 positionalArgs, IDictionary`2 namedArgs) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.Functions.cs:line 352
   at Robust.Shared.Localization.LocalizationManager.<>c__DisplayClass62_0.<AddCtxFunction>b__0(IList`1 args, IDictionary`2 options) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.Functions.cs:line 330
   at Linguini.Bundle.Resolver.WriterHelpers.Write(IInlineExpression self, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 166
   at Linguini.Bundle.Resolver.WriterHelpers.TryWrite(IExpression expression, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 73
   at Linguini.Bundle.Resolver.ResolverHelpers.Resolve(IInlineExpression self, Scope scope) in /_/Linguini.Bundle/Resolver/ResolverHelpers.cs:line 65
   at Linguini.Bundle.Resolver.WriterHelpers.TryWrite(IExpression expression, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 77
   at Linguini.Bundle.Resolver.Scope.MaybeTrack(TextWriter writer, Pattern pattern, IExpression expr) in /_/Linguini.Bundle/Resolver/Scope.cs:line 62
   at Linguini.Bundle.Resolver.WriterHelpers.Write(Pattern pattern, TextWriter writer, Scope scope) in /_/Linguini.Bundle/Resolver/WriterHelpers.cs:line 50
   at Linguini.Bundle.FluentBundle.TryGetMsg(String id, String attribute, IDictionary`2 args, IList`1& errors, String& message) in /_/Linguini.Bundle/FluentBundle.cs:line 241
   at Linguini.Bundle.FluentBundle.TryGetAttrMsg(String msgWithAttr, IDictionary`2 args, IList`1& errors, String& message) in /_/Linguini.Bundle/FluentBundle.cs:line 210
   at Robust.Shared.Localization.LocalizationManager.TryGetString(String messageId, String& value, Dictionary`2 args, FluentBundle bundle, CultureInfo culture) in RobustToolbox\Robust.Shared\Localization\LocalizationManager.cs:line 219"
   ```

Other than that, it works as expected. I am still not that happy with the Stamp border showing up. But that is something that should be discussed.

**Comment by TsjipTsjip** [comment]
> I am still not that happy with the Stamp border showing up. But that is something that should be discussed.

This is something that was already decided on, was hoping to at least get the basic functionality in for next session but no dice then.

**Comment by dffdff2423** [comment]
Sorry to bother, I was looking at this because I was considering porting it to CD. I am fairly certain that Delta-V is AGPL and you guys seem to be licensed under the MIT license. So this PR would technically violate the terms of the AGPL because it is a "viral" license.

**Comment by TsjipTsjip** [comment]
> Sorry to bother, I was looking at this because I was considering porting it to CD. I am fairly certain that Delta-V is AGPL and you guys seem to be licensed under the MIT license. So this PR would technically violate the terms of the AGPL because it is a "viral" license.

Your concern is correct. Closing this for now until we can find a way that sorts out licensing problems. I still want pen signing somehow as it is something that would contribute to a better roleplay environment for us.

**Pull request closed without merging**
