### PR TITLE
UI from verb to edit silicon laws

### PR DESCRIPTION
**Pull request by Simyon264**
TODO for upstream: Localisation
TODO for upstream: Make UI look better.

I really don't have any time left to make this look better for the sessions this week, so this will have to do. Since I plan on upstreaming it anyways, having no localisation should be no problem currently, as I will have to add it anyways during the "upstreaming" of this feature. TsjipTsjip, please don't murder me.

## About the PR

Adds a nice little UI to edit a silicons laws.
## Why / Balance

Funny law shenanigans.
## Technical details

Adds a new EUI (no idea what that is tbh, I just recreated what adminnotes do) which is responsible for setting and handeling the UI. 
Added method for setting laws in SiliconSystem.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
https://cdn.discordapp.com/attachments/1178043252969046030/1233105987561586749/Desktop_2024.04.25_-_19.18.36.02.mp4?ex=662be2f1&is=662a9171&hm=2adae473241bff03fc5f9a30cc3e2e0d99386a04c99fefefbb125b4a9e69f2ef&

**Changelog**

:cl: Simyon
ADMIN:
- add: In the Verb menu under Admin, you can now manage the laws of silicons. You can add new ones or remove them, as well as changin the text.

### CODE REVIEW

**Review by TsjipTsjip — DISMISSED** [review]
Works after rudimentary testing, does not work on entities that have been made lawbound by admin intervention. (Addition of components.) Idea for an admin smite?

Code review is still required before this PR is merged.

**Comment by Simyon264** [comment]
> Works after rudimentary testing, does not work on entities that have been made lawbound by admin intervention. (Addition of components.) ...

Weird, what components are you adding? `SiliconLawBoundComponent` is the only component it checks for when deciding to allow you to edit laws.

**Comment by TsjipTsjip** [comment]
> Weird, what components are you adding? `SiliconLawBoundComponent` is the only component it checks for when deciding to allow you to edit laws.

That's the one. Might be something with its defaults instead then.

**Comment by Simyon264** [comment]
I am investigating the issue.

**Comment by Simyon264** [comment]
So far, adding `SiliconLawBoundComponent` works and the Law UI open as well, but the affected player cannot view their own laws. After closing it and opening it again, I got an error.
```
[FATL] unhandled: Robust.Shared.Prototypes.UnknownPrototypeException: Unknown SiliconLawsetPrototype prototype: 
   at Robust.Shared.Prototypes.PrototypeManager.Index[T](String id) in D:\Projects\Sector-Umbra\RobustToolbox\Robust.Shared\Prototypes\PrototypeManager.cs:line 193
   at Content.Server.Silicons.Laws.SiliconLawSystem.GetLawset(String lawset) in D:\Projects\Sector-Umbra\Content.Server\Silicons\Laws\SiliconLawSystem.cs:line 281
```

I suspect the defaults are messed up.

**Comment by Simyon264** [comment]
It is indeed an issue with the SiliconLawProviderComponent. The default lawset prototype is empty.

**Comment by Simyon264** [comment]
Defaulting the default lawset prototype to crewsimov makes the law UI function without it crashing, however, the affected person is still unable to open the UI for their own laws.

**Comment by arimah** [comment]
Do you need to also add the client-side `SiliconLawBoundComponent`? That's what gives the player the 'view laws' action.

**Comment by Simyon264** [comment]
Closing this in favor for upstreaming, will upstream probably tmrw.

**Pull request closed without merging**
