### PR TITLE
THINGS FOR EVENT - DO NOT LOOK!!!

### PR DESCRIPTION
**Pull request by Boaz1111**
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Review by PursuitInAshes — CHANGES_REQUESTED** [review]
I'm unable to get these to show up ingame, so I can't really test. Are you able to get them to spawn ingame?
image

**Comment by Boaz1111** [comment]
I am. That's peculiar

**Review by PursuitInAshes — APPROVED** [review]
I have no clue what was wrong with my branch, but running it again it now shows up ingame alright.
Be sure to remind one of us to revert this once the event is complete

**Comment by Boaz1111** [comment]
It’s gear that will likely be used again in the future

**Pull request merged**
