### PR TITLE
Oral fidget toy

### PR DESCRIPTION
**Pull request by KittenColony**
## About the PR
Adds a chew toy to the good-clean-fun vender, for crew who have an oral fixation or teething issues

## Why / Balance
people were complaining they were getting chewed on

## Technical details
two YAML code lines, one new RSI folder

## Media
imageimage
imageimage
imageimage
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
nuh!

**Changelog**
:cl:

* add: Added a chew toy for the kob-- Crew.

### CODE REVIEW

**Comment by KittenColony** [comment]
oh its the wrong fucking catalog option

**Comment by KittenColony** [comment]
I'm competent I swear

**Comment by KittenColony** [comment]
ready for review / merging

**Comment by KittenColony** [comment]
they weld on my pipe till I yip

**Review by TsjipTsjip — APPROVED** [review]
GM approval in current state.

**Review by TsjipTsjip — APPROVED** [review]
Good to merge, tested in-game.

**Pull request merged**
