### PR TITLE
Renames the death squad hardsuit to internal affairs hardsuit

### PR DESCRIPTION
**Pull request by UltimateJester**
## About the PR

The deathsquad hardsuit has been renamed to the internal affairs hardsuit

## Why / Balance

NTIA is basically our death squad, however death squad is not real within NT. (This is also being done by Tsjip's request.)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

<!--
:cl:

### CODE REVIEW

**Comment by UltimateJester** [comment]
Alright my branch is no longer borked and changes have been labeled.

**Review by TsjipTsjip — CHANGES_REQUESTED** [review]
Can you take a quick skim through the codebase to also find other direct references to Death Squad? I think there's at least a uniform as well that needs renaming.

**Comment by Boaz1111** [comment]
Hardsuit helmet, pda, ID, backpack, jumpsuit, gas mask, also a poster mentioning deathsquad: PosterLegitEnlist

**Comment by TsjipTsjip** [comment]
@UltimateJester Are you coming back to this?

**Comment by PursuitInAshes** [comment]
I'll pickup the pr this weekend if nobody else does.

**Comment by ArtisticRoomba** [comment]
picking this up because i'm bored, expect a diff PR

**Comment by PursuitInAshes** [comment]
Refer to referenced PR for where this ended up.

**Pull request closed without merging**
