### PR TITLE
Personal Item: Entropy Rig

### PR DESCRIPTION
**Pull request by AjexRose**
## About the PR

Added a new personal item for new character of mine: The Entropy Rig. 
The entropy rig is designed to be a mobile medical device for a very rare and debilitating ailment, which makes it large, bulky, very obvious, and very heavy. 

## Why / Balance

Needed as it's practically the character's life support system.
## Media

Space Station 14 8_9_2024 9_28_28 PM
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: AjexRose
- add: Added new personal item for a new character

### CODE REVIEW

**Comment by AjexRose** [comment]
I have no clue about why theres all the weird null deletions at Resources/Prototypes/_Umbra/Loadouts/Miscellaneous/personal_items.yml

**Comment by AjexRose** [comment]
I also have no clue why the failed test mentions the container component despite never messing with it.

**Comment by SlamBamActionman** [comment]
Requires GM approval. To summarize the item's effects in plaintext:

- Personal item for Stella Viatrix.
- Outer Clothing (e.g. coat/hardsuit slot)
- Functionally similar to a normal (non-winter) coat item, including pockets, except for the following changes:
  - Causes a 20% slowdown when worn/held
  - Has a "hood" toggle, which equips the magnetic halo item.

image

Code otherwise looks good; I will provide a .yml file that does not have the nullspace changes via the Discord server.

**Comment by SlamBamActionman** [comment]
image
image

Side and back sprite

**Pull request closed without merging**
