### PR TITLE
More umbra figurines

### PR DESCRIPTION
**Pull request by Necro-a**
## About the PR

I made these for fun and figured i might as well PR them.
## Why / Balance

No real reason, they are simply neat :)
## Technical details

nuh uh
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

i dont think so.
**Changelog**

Added the Aaas-Las figurine.
Added the Loops-The-Horns figurine.
Added the Alma Vashli figurine.

### CODE REVIEW

**Review by TsjipTsjip — CHANGES_REQUESTED** [review]
This does not add the prototypes to the rolls for figurine boxes. Is this intentional? If not, check out:
`Resources/Prototypes/_Umbra/Entities/Objects/Fun/figurine_boxes.yml`
`Resources/Prototypes/_Umbra/Entities/Markers/Spawners/Random/toy.yml`

**Comment by Necro-a** [comment]
> This does not add the prototypes to the rolls for figurine boxes. Is this intentional? If not, check out: `Resources/Prototypes/_Umbra/Entities/Objects/Fun/figurine_boxes.yml` `Resources/Prototypes/_Umbra/Entities/Markers/Spawners/Random/toy.yml`

Right, i completely forgot about that! Let me fix that real quick.

**Review by SlamBamActionman — APPROVED** [review]
LGTM

Where's the Jalopy figurine? ;(

**Comment by Necro-a** [comment]
> LGTM
> 
> Where's the Jalopy figurine? ;(

When i make it! :)

**Comment by Kukutis96513** [comment]
hell yeah

**Pull request merged**
