### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by TsjipTsjip**
## About the PR

THUMP!

Also merges:
- https://github.com/cosmatic-drift-14/cosmatic-drift/pull/442 (Originally our contribution but was now backported to CD, so considered an upstream change from now on.)
- https://github.com/cosmatic-drift-14/cosmatic-drift/pull/446 (Which we already had? I think?)
- https://github.com/cosmatic-drift-14/cosmatic-drift/pull/449

THUMP!

Also reverts upstream changes:
- https://github.com/Sector-Umbra/Sector-Umbra/commit/8093a49943c621d381b04e54a6790f8b98b5813d

THUMP!

### CODE REVIEW

**Comment by Coolsurf6** [comment]
**THUMP!**

**Comment by Simyon264** [comment]
Everything I tested is working as intended or the issues found are not relevant to the upstream merge.
**Thing tested:**
- Character editor.
- Game ticker (round flow, events etc.)
- Combat
- Employment records computer
- Botany (man this shit is boring; how do people play this)
- Security records computer

**Issues found:**
- Security records computer:
Setting the status of a person does not update the dropdown client side. The status is however set and reopening the UI fixes it.
This isn't really an "us" issue. I assume this is an upstream issue.

**Notes:**
- The migrations still seem rather high? On localhost 3 of the 5 events were migration events. I believe this could be because of the min player count of some other events?
- Fish.

**Comment by TsjipTsjip** [comment]
Gonna assume records computer is indeed an upstream issue, though I will track it down properly later.

As for the event scheduler, yeah, I've been trying to orient it around 30 to 40 players. Unscheduled shifts use the extended scheduler (when people request it).

**Comment by PursuitInAshes** [comment]
> Gonna assume records computer is indeed an upstream issue, though I will track it down properly later.

There was CD PR maybe fixing something like this a while ago, I assume we grabbed it though, so I'm not entirely sure.

>  I've been trying to orient it around 30 to 40 players.

It may be worth dropping the weight of the vent critter events overall, with the addition of snakes, they were not re-balanced or returned so they are all very common at present.

**Comment by TsjipTsjip** [comment]
> It may be worth dropping the weight of the vent critter events overall, with the addition of snakes, they were not re-balanced or returned so they are all very common at present.

Will address this in a later PR, need to get the required things in for today's session first.

**Pull request merged**
