### PR TITLE
Fishbowl - Central Commander personal transport/office shuttle

### PR DESCRIPTION
**Pull request by Tych0theSynth**
## About the PR

Added the Fishbowl, a small shuttle intended as a transport/office for an individual central commander.
The name and design is taken from the slang term for those managers offices which are made entirely of glass, so they can keep an eye on their delegates and so that said delegates always know they're being watched. 
This shuttle is intended only for admin usage.

## Why / Balance

It was identified that there was a gap that could be filled by such a shuttle, so I made one. 
Flies just fine, is pretty agile. 
APUs provide enough power for all thrusters and other machinery.
All doors are CC locked, aside from the external docks. 
Basic sustenance supplies and a coffee machine in case you're out there for a while. Also so you can grab a hot drink prior to a meeting.
The computer is an employee records computer and fax is a CC fax.

## Technical details

.yml

## Media
2024-04-16 22_37_19-Window
Uninitialised, showing subfloor and spawns with balanced lighting.

2024-04-16 22_37_48-Window
Uninitialised, lights on.

2024-04-16 22_39_14-Window
Post init.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None.

**Changelog**

:cl:
- add: Added the Fishbowl, a personal transport/office for CC commanders.

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
Added posters and collision lighting.

**Comment by Tych0theSynth** [comment]
Removed fax after feedback. Hot drinks machine has been moved into the office, a water cooler has been added along with a friend. Screenshots updated accordingly.

**Comment by Simyon264** [comment]
I really like the little NAV lights around the thrusters.

**Comment by Tych0theSynth** [comment]
> I really like the little NAV lights around the thrusters.

I'm a ship nerd. I have to do it.

**Review by TsjipTsjip — CHANGES_REQUESTED** [review]
Presently, this map fails to load locally with the following server log:
```log
[INFO] con: localhost@TheTsjipster:loadgrid 17 /Maps/_Umbra/fishbowl.yml 20 0
[INFO] loader: No user map found: /Maps/_Umbra/fishbowl.yml
[INFO] loader: Loading Map: /Maps/_Umbra/fishbowl.yml
[ERRO] loader: Missing prototype for map: NT Fishbowl
[ERRO] loader: Found missing prototypes in map file. Missing prototypes have been dumped to logs.
```

Somewhat unhelpfully, it does not actually tell me where those "logs" are.

**Comment by Tych0theSynth** [comment]
> Presently, this map fails to load locally with the following server log:
> 
> ```
> [INFO] con: localhost@TheTsjipster:loadgrid 17 /Maps/_Umbra/fishbowl.yml 20 0
> [INFO] loader: No user map found: /Maps/_Umbra/fishbowl.yml
> [INFO] loader: Loading Map: /Maps/_Umbra/fishbowl.yml
> [ERRO] loader: Missing prototype for map: NT Fishbowl
> [ERRO] loader: Found missing prototypes in map file. Missing prototypes have been dumped to logs.
> ```
> 
> Somewhat unhelpfully, it does not actually tell me where those "logs" are.

What in the hell? Alright. I'll test and try and work out what's wrong.

**Review by TsjipTsjip — APPROVED** [review]
Works on my machine. Will probably shift this file around slightly when we end up adding our own shuttles to this folder.

**Pull request merged**
