### PR TITLE
Bluespace Jug

### PR DESCRIPTION
**Pull request by Necro-a**
## About the PR
I added a bluespace beaker, an addition to the T3 service research for bluespace stuff.

## Why / Balance
It fills a missing spot in terms of medical bluespace items, as currently there are only the bluespace beakers and syringes. I also wanted to add a way to simplify the process of refilling the chemical dispensers, while also adding something to give the bluespace beakers more usage.

## Technical details
Added sprites, and code for the bluespace jug

## Media
image

## Breaking changes

**Changelog**
:cl:
- Added the bluespace jug

### CODE REVIEW

**Comment by arimah** [comment]
This pull request does two completely unrelated things. To make it easier to manage and follow changes, it should be split into two PRs – one for the new bluespace jug, another for the cargo telepad removal. :)

**Comment by Necro-a** [comment]
> This pull request does two completely unrelated things. To make it easier to manage and follow changes, it should be split into two PRs – one for the new bluespace jug, another for the cargo telepad removal. :)

In that case, should i be closing this PR and making 2 new, seperate ones, or does it not matter?

**Comment by arimah** [comment]
> In that case, should i be closing this PR and making 2 new, seperate ones, or does it not matter?

You don't have to close this one. You can update this PR to include only one of the changes, just remember to update the description so we can tell at a glance what this one does. :D

**Comment by Necro-a** [comment]
> > In that case, should i be closing this PR and making 2 new, seperate ones, or does it not matter?
> 
> You don't have to close this one. You can update this PR to include only one of the changes, just remember to update the description so we can tell at a glance what this one does. :D

Alright! How does it look now? Didnt mess anything up, did i?

**Comment by TsjipTsjip** [comment]
Closing this because we will not be merging a bluespace jug currently, as discussed on discord before with the PR author.

**Pull request closed without merging**
