### PR TITLE
Personal Item: John Morwood's Military Cross

### PR DESCRIPTION
**Pull request by Coolsurf6**
## About the PR
Added a personal item for 'John Morwood' for jmp723

## Why / Balance
Personal Item.

## Technical details
Added new YML code based off the ClothingNeckBase. Sprited by [Waiting for Name for spriter]

## Media

Screenshot_20241117_223517

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added John Morwood's Military Cross.

### CODE REVIEW

**Comment by TsjipTsjip** [comment]
I believe this was sprited by GhostPrince (ghostprince on discord).

**Comment by Coolsurf6** [comment]
Yoink....

**Comment by Coolsurf6** [comment]
I will wait for jmp to message back just to confirm before I put someones username on the repo.

**Review by PursuitInAshes — APPROVED** [review]
Works ingame.

**Pull request merged**
