### PR TITLE
Personal Item: Drugeristic Suit

### PR DESCRIPTION
**Pull request by TheNarwhalrus**
## About the PR
Added personal item for Druger Phillips Ruger Dug for player Xolotl

## Why / Balance
Personal Item

## Technical details
Added new YML code for drugeristic suit in jumpsuits.yml. Added new sprites based off of of lawyersuitblack.

## Media
image
image2

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added Druger's personal item; Drugeristic Suit!

### CODE REVIEW

**Comment by TheNarwhalrus** [comment]
Still needs to be added to the loadout.

**Comment by Coolsurf6** [comment]
We Ball

**Comment by Coolsurf6** [comment]
Remember to set the PR to open, not draft btw. Should be ready

**Comment by TheNarwhalrus** [comment]
Should be ready for review

**Review by TsjipTsjip — APPROVED** [review]

**Pull request merged**
