### PR TITLE
Personal Item: Walks-The-Grooves Plushie

### PR DESCRIPTION
**Pull request by Coolsurf6**
## About the PR
Added a personal item for 'Walks-The-Graves' for luckyshotpictures

## Why / Balance
Personal Item.

## Technical details
Added new YML code using the base lizard plushie item. Edited images of the PlushieLizard including the headsprite done by Nikovnik!

## Media

Screenshot_20241121_204226

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Walks-The-Grooves Plushie. Graves would be proud!

### CODE REVIEW

**Comment by Coolsurf6** [comment]
TODO:

- [ ] Description of Plushie
- [ ] Headsprites for being equipped
- [X] Get called something _cutely_

**Review by TsjipTsjip — APPROVED** [review]

**Comment by TsjipTsjip** [comment]
GM approval.

**Comment by Coolsurf6** [comment]
Images added, awaiting the Description and this can be opened!

**Comment by Coolsurf6** [comment]
Realise this is done so whoops.

**Pull request merged**
