### PR TITLE
Forehead ring marking

### PR DESCRIPTION
**Pull request by Necro-a**
## About the PR

Added the fabled onion ring. Tormentor of Necroa (me) 
## Why / Balance

Because everyone keeps joking about the onion ring so you know what? Now you can make fun of it in character too!
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image

**Changelog**

-added onoin reng :3

### CODE REVIEW

**Review by SlamBamActionman — APPROVED** [review]
onyon

Code looks good, so does sprite. Personally I would add a slightly grayer pixel to complete the ring on the front sprite like below, but either way it still looks good :) 
image

**Comment by Necro-a** [comment]
> Onion is kind of an OOC reference and should not be referred to as-such in-character. How about: `Forehead Tattoo (Ring)` (as suggested by Arimah)

fair. May i keep it as onion ring in the files though? Just dont have it be onion ring ingame.

**Review by SlamBamActionman — COMMENTED** [review]
You're gonna wanna change the first line that says "Onion" as well (e.g. "Forehead Tattoo"), as if I recall correctly it is what shows up as a title for the color selection part when editing markings.

**Comment by Necro-a** [comment]
> You're gonna wanna change the first line that says "Onion" as well (e.g. "Forehead Tattoo"), as if I recall correctly it is what shows up as a title for the color selection part when editing markings.

fixed.

**Pull request merged**
