### PR TITLE
Revives Iris

### PR DESCRIPTION
**Pull request by PursuitInAshes**
## About the PR
Revives #68 ..

## Why / Balance
Custom maps are positive and reduce maintenance burden in the event we stray further from upstreams content.

## Media
Iris-0

## Breaking changes
Makes changes to the PostMapInitTest. Should not cause issues, but worth mentioning.

**Changelog**
Iris Real™. This facility contains a Food Court housing the bar, hydroponics and kitchen as well as the entertainment section. Medical features a psychological, viro and emergency wing. Security is centered at the core with a nice perma, well-stocked armory and evidence storage. [Should probably link the map render too.]

(No, I'm not writing a properly formatted admin CL entry for this.)
Admin CL:
Iris has been added. an approximately 25 to 60 player map, take it into consideration whenever running a map vote.

### CODE REVIEW

**Comment by luckyshotpictures** [comment]
Are you sure you want me to review my own map?

**Comment by Simyon264** [comment]
I will take a look soon

**Review by Simyon264 — CHANGES_REQUESTED** [review]
See https://canary.discord.com/channels/1178043252969046027/1239998429040742522 for review

**Comment by TsjipTsjip** [comment]
@PursuitInAshes Is this up to date with latest? I'll get around to a full map review later.

**Pull request merged**
