### PR TITLE
Add's a jacket personal Item for Sphiral/Nova

### PR DESCRIPTION
**Pull request by SphiraI**
## About the PR
Title! Adds a custom jacket for Nova Gem.

## Why / Balance
Canonically, she has a jacket that she tries to wear in any sector that lets her, and now she's put in her request to have it in Umbra! The comfort of her own personal jacket would of course mean quicker healing too!... and maybe less floor laying...? (~~definitely means more floor time~~)

## Technical details
Adds a prototype for her jacket, and a hood proto for her ears. (The ears are a toggle action of the coat)

## Media
*updated 7/19/2024 to include the cat ears as well*
image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: Sphiral
- add: Added Nova's custom comfy coat!

### CODE REVIEW

**Review by SlamBamActionman — APPROVED** [review]
Please post screenshots for how it looks like when the ears are applied as that is currently missing.

Codewise it looks good; it is more complex than a standard item, but only in terms of visuals and it looks like it has been implemented correctly. 

Be aware that, while unlikely, it is possible another character could put on the item and thus apply the slime cat ears. If that is undesirable and always having cat ears on would be preferred, PRing the cat ears as a markings customization is also an option.

Requires a game master review to be merged.

**Review by TsjipTsjip — APPROVED** [review]
GM approval under exact reskin rule.

**Comment by SphiraI** [comment]
> Please post screenshots for how it looks like when the ears are applied as that is currently missing.
Gah, forgot about those! I'll update the pictures right now


> Be aware that, while unlikely, it is possible another character could put on the item and thus apply the slime cat ears. If that is undesirable and always having cat ears on would be preferred, PRing the cat ears as a markings customization is also an option.

Technically, yeah, it is undesirable, but I'm personally fine with the small niche possibility. It would be a lot more work, and take a lot more implementation to get working otherwise (making RGB colorable, personal markings, Alpha slider, etc). I don't really have the knowledge to do that, so I opted for the easier route.

**Comment by SphiraI** [comment]
@SlamBamActionman (I think this is how git pinging works)
Pictures updated.
Extra cat ears info in case it's relevant:
The cat ears are just a near copy paste of the normal item. The texture was color shifted, made transparent, and had a couple extra pixels added to give that "slime drip" feel to them. That aside, the proto is the same, but changed name/description, and made abstract.

**Comment by SlamBamActionman** [comment]
> Technically, yeah, it is undesirable, but I'm personally fine with the small niche possibility. It would be a lot more work, and take a lot more implementation to get working otherwise (making RGB colorable, personal markings, Alpha slider, etc). I don't really have the knowledge to do that, so I opted for the easier route.

All good; we don't have personal markings right now and like you say that would probably be a bunch of work to get working. Our current standard is that custom markings are publicly available (though some, like Necroa Thrii-Cree's moth forehead ring marking, are unique enough that others are unlikely to use it). I have never seen anyone wear someone else's personal item anyway so while it is technically possible I doubt it's gonna be an actual issue. 

And personally I think it's pretty cool that it's a toggleable feature! Morphing like that fits a slimeperson character! :D 

komi-san-komi-cant-communicate

**Pull request merged**
