### PR TITLE
Personal Item: Hisses-At-Inconvenience's Golden Locket

### PR DESCRIPTION
**Pull request by Coolsurf6**
## About the PR
Added a personal item for 'Hisses-At-Inconvenience' for Akira 

## Why / Balance
Personal Item.

## Technical details
Added new YML code using the outer clothing base item. Akira created the icon and clothing item sprites. 

The item can be toggled similar to magboots using the ItemToggle component which swaps its icon between icon and icon-on to open and close the locket. 

There is a sound that will play when opening and closing. This item has a delay of 0.5 seconds to prevent a spam of this sound. 

## Media
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**

:cl:
- add: Added Hisses-At-Inconvenience's personal golden locket!

### CODE REVIEW

**Comment by Coolsurf6** [comment]
> If it’s just a locket, shouldn’t it be neckwear?

Akira wanted it to be on the outerclothing item, not on the scarf/cosmetic item slot. It is a quick change if it is absolutely mandatory to not have it as an outerwear item.

**Comment by Boaz1111** [comment]
Ah. If that’s what they want

**Comment by Coolsurf6** [comment]
Looks about right, just want to check tests and get a review of the copyright!

**Comment by Coolsurf6** [comment]
Line 18 allows the item to be used in hand without auto equioping. I think the yml is supposed to be quickEquip not quickequip. Will look at. 

I am unsure about line 23, I believe I just followed how magboots did I believe. Might be something we have to go over together actively in a chat

**Comment by Coolsurf6** [comment]
Error about python installation? I did check that I could actually do the YAML linter on my own system which was good. Should be done now.

**Pull request merged**
