### PR TITLE
Change all IC mention of NT Death Squads to the NTIA

### PR DESCRIPTION
**Pull request by ArtisticRoomba**
## About the PR
Changed all IC mention of death squads to the NTIA, NT's Internal Affairs agents.

This is a pickup of PR #219 

## Why / Balance
I was bored

Mirrored reasoning from #219:

> NTIA is basically our death squad, however death squad is not real within NT. (This is also being done by Tsjip's request.)

## Technical details
All IC mention of death squads were changed to NTIA. Non player-facing things like protos were kept the same because god I do not hate myself today.

## Media
Content Client_zotn0ygfrW
Content Client_JDpccNw9fY
Content Client_nqv0FYBtGM
Content Client_24cpfw7RAJ

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: All IC references to Death Squads were renamed to Internal Affairs Agents.

### CODE REVIEW

**Comment by ArtisticRoomba** [comment]
I don't know why I am a contributor of this fork already but that's how it is I guess

**Comment by PursuitInAshes** [comment]
> I don't know why I am a contributor of this fork already but that's how it is I guess
I believe that if you have contributed to wizden you will automatically be marked a contrib here aswell due to how things were set up a long time ago.

Anyways, I'll get a review done sometime today, if I forget ping me on the discord please.

**Comment by ArtisticRoomba** [comment]
> > I don't know why I am a contributor of this fork already but that's how it is I guess
> 
> 
> 
> I believe that if you have contributed to wizden you will automatically be marked a contrib here aswell due to how things were set up a long time ago.
> 
> 
> 
> Anyways, I'll get a review done sometime today, if I forget ping me on the discord please.


Thanks. I already know I missed one umbra marker I forgot to put lol.

**Review by PursuitInAshes — CHANGES_REQUESTED** [review]
I am fairly certain FTL files can take markdown of somekind. Fact check me and if I'm wrong I'll dismiss this as stale.
Either mark the individual lines with `# whatever` or above and below our changes please.

**Comment by ArtisticRoomba** [comment]
yeah should have been obvious on my side ¯\_(ツ)_/¯
you learn something new every day

**Review by PursuitInAshes — CHANGES_REQUESTED** [review]
In `Resources/Prototypes/Entities/Objects/Devices/pda.yml` there is the deathsquad PDA on LN 780 with the deathsquad suffix still. If you could change that too, it would be appreciated.

Additionally, I'm going to go back on what I said (I'm so sorry), if you could have the FTL markdown be on the same line as the change, it would be appreciated. I tested in game and this shouldn't cause any issues. (Ex: `ghost-role-information-Death-Squad-name = Internal Affairs Agent # Umbra Change`, but if it gives you any issues let me know

Thanks a lot for picking this PR up and dealing with me changing my mind halfway through

**Comment by Boaz1111** [comment]
From what I recall, that does cause issues

**Comment by PursuitInAshes** [comment]
So turns out I was wrong and my localhost gaslit me. Ignore my requests to change the FTL files.

**Review by PursuitInAshes — APPROVED** [review]
Works ingame. (Sorry again)

**Pull request merged**
